export const START_TIME = "startTime"
export const PLAY_LIST_DETAIL = "playListDetail"
export const PLAY_LIST = "playList"
export const PAGE = "page"
export const CURRENT_SONG_INDEX = "currentSongIndex"
export const PLAY_STATUS = "playStatus"
export const DURATION = "duration"
export const VOLUME = "volume"
export const AUDIO_SRC = "audioSrc"

